---
# This file is used to cleanup OpenStack neutron resources

- name: Cleanup routers
  os_router:
      cloud: "{{ provisioner.cloud | default(omit) }}"
      name: "{{ prefix }}{{ item.value.name | default(router_name) }}"
      state: absent
  with_dict: "{{ provisioner.neutron.routers }}"
  when: provisioner.neutron.routers is defined
  register: routers
  ignore_errors: yes

- name: Cleanup subnets
  os_subnet:
      cloud: "{{ provisioner.cloud | default(omit) }}"
      name: "{{ prefix }}{{ item.value.name }}"
      state: absent
  with_dict: "{{ provisioner.neutron.subnets }}"
  when: provisioner.neutron.subnets is defined
  register: subnets
  ignore_errors: yes

- name: Cleanup networks
  os_network:
      cloud: "{{ provisioner.cloud | default(omit) }}"
      name: "{{ prefix }}{{ item.value.name }}"
      state: absent
  with_dict: "{{ provisioner.neutron.networks }}"
  when: provisioner.neutron.networks is defined
  register: networks
  ignore_errors: yes

#TODO(abregman): Enable 'security groups' task when ansible 2.1 is out
#- name: Cleanup security groups
#  os_security_group:
#      cloud: "{{ provisioner.cloud | default(omit) }}"
#      name: "{{ prefix }}{{ item.value.name | default(security_group_name) }}"
#      state: absent
#  register: security_groups
#  with_dict: "{{ provisioner.neutron.security_groups }}"
#  when: provisioner.neutron.security_groups is defined

- name: Fail run if one of neutron cleanups tasks failed/skipped
  fail: msg="The run failed because one of neutron cleanup tasks failed/skipped"
  when: (routers|skipped or subnets|skipped or networks|skipped)
